import { IHardSkill } from '@types';
import {
  Android,
  Angular,
  Azure,
  Csharp,
  Docker,
  DotNet,
  Expo,
  Ios,
  Mysql,
  Nextjs,
  Php,
  Pinia,
  Quasar,
  React,
  ReactNative,
  Stripe,
  Symfony,
  Tailwind,
  Typescript,
  Vite,
  Vuedotjs,
} from '@logos';

export const PROFILE_HARD_SKILLS: IHardSkill[] = [
  { label: 'PHP', logo: Php, isOnMain: true, url: 'https://www.php.net/' },
  { label: 'MySQL', logo: Mysql, isOnMain: true, url: 'https://www.mysql.com/fr/' },
  { label: 'React', logo: React, isOnMain: true, url: 'https://react.dev/' },
  { label: 'TypeScript', logo: Typescript, isOnMain: true, url: 'https://www.typescriptlang.org/' },
  { label: 'Expo', logo: Expo, isOnMain: true, url: 'https://expo.dev/' },
  { label: 'C#', logo: Csharp, isOnMain: true, url: 'https://learn.microsoft.com/en-us/dotnet/csharp/' },
  { label: 'Angular', logo: Angular, isOnMain: true, url: 'https://angular.io/' },
  { label: 'Symfony', logo: Symfony, isOnMain: true, url: 'https://symfony.com/' },
  { label: 'Vue.js', logo: Vuedotjs, isOnMain: true, url: 'https://vuejs.org/' },
  { label: 'Pinia', logo: Pinia, isOnMain: true, url: 'https://pinia.vuejs.org/' },
  { label: 'Vite', logo: Vite, isOnMain: true, url: 'https://vitejs.dev/' },
  { label: 'React Native', logo: ReactNative, isOnMain: true, url: 'https://reactnative.dev/' },
  { label: 'Next.js', logo: Nextjs, isOnMain: true, url: 'https://nextjs.org/' },
  { label: '.NET', logo: DotNet, isOnMain: true, url: 'https://dotnet.microsoft.com/' },
  { label: 'Azure', logo: Azure, isOnMain: true, url: 'https://azure.microsoft.com/' },
  { label: 'Docker', logo: Docker, isOnMain: false, url: 'https://www.docker.com/' },
  { label: 'Quasar', logo: Quasar, isOnMain: true, url: 'https://quasar.dev/' },
  { label: 'Stripe', logo: Stripe, isOnMain: true, url: 'https://stripe.com/' },
  { label: 'Tailwind', logo: Tailwind, isOnMain: true, url: 'https://tailwindcss.com/' },
  { label: 'Ios', logo: Ios, isOnMain: false, url: 'https://www.apple.com/ios/app-store/' },
  { label: 'Android', logo: Android, isOnMain: false, url: 'https://www.android.com/' },
];
